<?php
/** @var $block \Sfedu\ShopsManage\Block\ReviewForm */
/**  @var $escaper \Magento\Framework\Escaper */
/** @var \Sfedu\ShopsManage\Block\ReviewList $reviewList */
$reviewList = $this->getChildBlock('shop.reviews.list');
?>

<div class="block-content review">
    <h2><?= __('Reviews') ?></h2>
    <?= $reviewList->toHtml(); ?>
    <?php if ($block->getAllowWriteReviewFlag()):?>
        <form action="<?= $escaper->escapeUrl($block->getAction()) ?>" class="review-form" method="post" id="review-form" data-role="shop-review-form" data-bind="scope: 'review-form'">
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset review-fieldset" data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
                <legend class="legend review-legend"><strong><span><?= $escaper->escapeHtml(__("Write Your Own Review")) ?></span></strong></legend> <br/>
                <?php if ($block->getRatings()): ?>
                    <span id="input-message-box"></span>
                    <fieldset class="field required review-field-ratings">
                        <legend class="label"><span><?= $escaper->escapeHtml(__('Your Rating')) ?></span></legend><br/>
                        <div class="control">
                            <div class="nested" id="shop-review-table">
                                <?php foreach ($block->getRatings() as $_rating): ?>
                                    <div class="field choice review-field-rating">
                                        <label class="label" id="<?= $escaper->escapeHtml($_rating->getId()) ?>_rating_label"><span><?= $escaper->escapeHtml($_rating->getName()) ?></span></label>
                                        <br>
                                        <div class="control review-control-vote-multistar">
                                            <?php $starsNum = $_rating->getStarsNum();?>
                                            <?php for ($iterator = $starsNum; $iterator>=1; $iterator--):?>

                                                <input
                                                    type="radio"
                                                    name="ratings[<?= $escaper->escapeHtmlAttr($_rating->getId()) ?>]"
                                                    id="rating_star_<?= $escaper->escapeHtmlAttr($_rating->getId()) ?>_<?= $escaper->escapeHtmlAttr($iterator) ?>"
                                                    value="<?= $escaper->escapeHtmlAttr($iterator) ?>"
                                                    class="radio"
                                                    data-validate="{'rating-required':true}"
                                                    aria-labelledby="<?= $escaper->escapeHtmlAttr($_rating->getId()) ?>_rating_label <?= $escaper->escapeHtmlAttr($_rating->getId()) ?>_<?= $escaper->escapeHtmlAttr($iterator) ?>_label" />

                                                <label
                                                    class="rating-star"
                                                    for="rating_star_<?= $escaper->escapeHtmlAttr($_rating->getId()) ?>_<?= $escaper->escapeHtmlAttr($iterator) ?>"
                                                    title="<?= $escaper->escapeHtmlAttr(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>"
                                                    id="<?= $escaper->escapeHtmlAttr($_rating->getId()) ?>_<?= $escaper->escapeHtmlAttr($iterator) ?>_label">
                                                    <span><?= $escaper->escapeHtml(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?></span>
                                                </label>
                                            <?php endfor; ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                        </div>
                    </fieldset>
                <?php endif ?>
                <div class="field review-field-nickname required">
                    <label for="nickname_field" class="label"><span><?= $escaper->escapeHtml(__('Nickname')) ?></span></label>
                    <div class="control">
                        <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
                    </div>
                </div>
                <div class="field review-field-summary required">
                    <label for="summary_field" class="label"><span><?= $escaper->escapeHtml(__('Summary')) ?></span></label>
                    <div class="control">
                        <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
                    </div>
                </div>
                <div class="field review-field-text required">
                    <label for="review_field" class="label"><span><?= $escaper->escapeHtml(__('Review')) ?></span></label>
                    <div class="control">
                        <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar review-form-actions">
                <div class="primary actions-primary">
                    <button type="submit" class="action submit primary"><span><?= $escaper->escapeHtml(__('Submit Review')) ?></span></button>
                </div>
            </div>
        </form>
        <script type="text/x-magento-init">
{
    "[data-role=shop-review-form]": {
        "Magento_Ui/js/core/app": {
            "components": {
                "review-form": {
                    "component": "Sfedu_ShopsManage/js/review/review"
                }
            }
        }
    },
    "#review-form": {
        "Sfedu_ShopsManage/js/review/error-placement": {},
        "Sfedu_ShopsManage/js/review/validate-review": {},
        "Magento_Review/js/submit-review": {}
    }
}
</script>
    <?php else: ?>
        <div class="message info notlogged" id="review-form">
            <div>
                <?= $escaper->escapeHtml(__('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
            </div>
        </div>
    <?php endif ?>
</div>
